import React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./styles/globals.css"
import { NextIntlClientProvider } from "next-intl"
import { StoreProvider } from "./StoreProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Assistant on Next.js",
  description: "Generated by create next app",
}

export async function generateStaticParams() {
  return [{ lang: "en-GB" }]
}

interface RootLayoutProps {
  children: React.ReactNode
  params: Promise<{ lang?: string }>
}

export default async function RootLayout({ children, params }: Readonly<RootLayoutProps>) {
  return (
    <StoreProvider>
      <html lang={(await params).lang}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </body>
      </html>
    </StoreProvider>
  )
}
